name: 'Code Owners'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled

concurrency:
  group: codeowners-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  codeowners:
    name: 'Run Codeowners Plus'
    runs-on: ubuntu-latest

    permissions:
      contents: read # required for @actions/checkout

    steps:
      - name: 'Checkout Code Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Codeowners Plus'
        uses: multimediallc/codeowners-plus@3cbd622a12077bfd0f2dfcabd6c01177fb343c4c # v1.3.2
        with:
          github-token: '${{ secrets.PAT_GITHUB_TOKEN }}'
          pr: '${{ github.event.pull_request.number }}'
          verbose: true
          quiet: ${{ github.event.pull_request.draft }}
