name: 'Rerun Code Owners'

on:
  pull_request_review:
    types:
      - submitted

permissions: {}

jobs:
  rerun-codeowners:
    name: 'Rerun Codeowners Plus'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout Code Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Rerun Checks'
        uses: shqear93/rerun-checks@cafa5c1c11c880f9b23e6a73ad8628483fdae798  # @v3
        with:
          github-token: '${{ secrets.PAT_GITHUB_TOKEN }}'
          check-names: 'Run Codeowners Plus'
